version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - 2717:27017
    volumes:
      - ./databases:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234